FROM alpine:3.16 as node-alpine-3-16

RUN apk add --upgrade --no-cache nodejs npm
RUN apk add --upgrade --no-cache bash

RUN mkdir -p /home/app
WORKDIR /home/app

COPY . /home/app

RUN npm install
RUN npm run build
RUN rm -rf node_modules
RUN npm install --production

CMD ["npm", "start"]
