FROM alpine:3.16 as node-alpine-3-16

RUN apk add --upgrade --no-cache nodejs nodejs-npm
RUN apk add --upgrade --no-cache bash

RUN mkdir -p /home/app
WORKDIR /home/app

COPY . /home/app

CMD ["npm", "start"]
